on: [push, pull_request]

name: Valgrind Memory Check

jobs:
  valgrind:
    name: Memory Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # - name: Install valgrind
      #   run: sudo apt install -y valgrind

      - name: Install valgrind
        run: |
          sudo apt update && sudo apt install -y libclang-dev libc6-dbg \
          && wget -O valgrind.tar.bz2 https://sourceware.org/pub/valgrind/valgrind-3.23.0.tar.bz2 \
          && mkdir valgrind && tar -xvjf valgrind.tar.bz2 -C valgrind --strip-components=1 \
          && cd valgrind && ./configure && make && sudo make install

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: "--example containers --features 'anyhow backtrace chrono uuid'"

      - name: Run valgrind
        run: valgrind --error-exitcode=1 --leak-check=full --suppressions=valgrind.supp ./target/debug/examples/containers
